2023-04-19 06:05:18 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-19 06:05:18 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-19 06:05:18 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/2/logs.log
2023-04-19 06:05:18 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:18 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:18 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:18 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-19 06:05:18 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:18 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:18 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.7.1 exists...
2023-04-19 06:05:18 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.7.1 was found locally.
2023-04-19 06:05:18 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-check-21-2-qwqjn with resources io.airbyte.config.ResourceRequirements@33f9a520[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:18 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/2 --log-driver none --name source-customize-api-check-21-2-qwqjn --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.7.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/source-customize-api:0.7.1 check --config source_config.json
2023-04-19 06:05:18 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Attempting to connect to API at http://192.168.100.158:9098/category/build/0/unauthorized...
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Response from http://192.168.100.158:9098/category/build/0/unauthorized: {'status': 0, 'message': None, 'data': [{'id': 1, 'name': 'Êï∞ÊçÆ‰ªìÂ∫ìÊ®°Âùó', 'description': 'Êï∞ÊçÆ‰ªìÂ∫ìÊ®°Âùó', 'parentId': None, 'idPath': None, 'params': None, 'systems': None, 'sort': 0, 'type': 0, 'status': 0, 'namespace': None, 'groupId': None, 'groupName': None, 'createTime': '2022-12-09T15:45:16', 'createBy': 'admin', 'updateTime': '2022-12-09T15:45:16', 'updateBy': 'admin', 'tagCount': 7, 'children': None, 'scopes': [{'id': 3, 'name': 'Êï∞ÊçÆÈõÜ', 'systemId': 1}]}], 'error': None}
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection status: True
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection success
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check succeeded
2023-04-19 06:05:19 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@24e6636f[status=succeeded,message=<null>,additionalProperties={}]
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/2/logs.log
2023-04-19 06:05:19 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:19 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:19 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-19 06:05:19 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-19 06:05:19 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-check-21-2-vuuax with resources io.airbyte.config.ResourceRequirements@33f9a520[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:19 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/2 --log-driver none --name destination-mysql-check-21-2-vuuax --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/destination-mysql:0.1.20 check --config source_config.json
2023-04-19 06:05:19 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Class path contains multiple SLF4J bindings.
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-19 06:05:20 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: CHECK"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:20 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:20 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL"
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting..."
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed."
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(close):350 - HikariPool-1 - Shutdown initiated..."
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(close):352 - HikariPool-1 - Shutdown completed."
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:21 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:21 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@3e7cb26[status=succeeded,message=<null>,additionalProperties={}]
2023-04-19 06:05:21 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:21 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-19 06:05:21 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/2/logs.log
2023-04-19 06:05:21 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):93 - Setting up source...
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):97 - Setting up destination...
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-19 06:05:21 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):106 - Setting up replication worker...
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 21 attempt id: 2
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:21 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.my_stream=full_refresh - overwrite}
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:21 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:21 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:21 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-19 06:05:22 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-19 06:05:22 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-21-2-ywlek with resources io.airbyte.config.ResourceRequirements@4b1fbdd[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:22 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/2 --log-driver none --name destination-mysql-write-21-2-ywlek --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-19 06:05:22 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-19 06:05:22 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:22 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:22 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.7.1 exists...
2023-04-19 06:05:22 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.7.1 was found locally.
2023-04-19 06:05:22 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-21-2-iidfg with resources io.airbyte.config.ResourceRequirements@629faf59[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:22 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/2 --log-driver none --name source-customize-api-read-21-2-iidfg --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.7.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/source-customize-api:0.7.1 read --config source_config.json --catalog source_catalog.json
2023-04-19 06:05:22 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:22 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-19 06:05:22 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-19 06:05:22 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-19 06:05:22 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:22 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:22 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:23 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-19 06:05:23 [44msource[0m > 'dict' object is not callable
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
2023-04-19 06:05:23 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting..."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=my_stream, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_zjm_my_stream, outputTableName=_airbyte_raw_my_stream, syncMode=overwrite}"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream my_stream. schema: api, tmp table name: _airbyte_tmp_zjm_my_stream"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream my_stream. schema api, tmp table _airbyte_tmp_zjm_my_stream, final table _airbyte_raw_my_stream"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream my_stream. schema api, tmp table name: _airbyte_tmp_zjm_my_stream"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed."
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:23 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:23 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	... 4 more
2023-04-19 06:05:23 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1681884321905,
  "endTime" : 1681884323838,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1681884323835,
    "destinationWriteStartTime" : 1681884322111,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1681884323837,
    "replicationStartTime" : 1681884321905,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1681884322034,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-19 06:05:23 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "'dict' object is not callable",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 2,
    "jobId" : 21,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 110, in read\n    stream_is_available, error = stream_instance.check_availability(logger, self)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 190, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 45, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 423, in read_records\n    yield from self._read_pages(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 439, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 456, in _fetch_next_page\n    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),\nTypeError: 'dict' object is not callable\n",
  "timestamp" : 1681884323104
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 2,
    "jobId" : 21,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1681884323282
} ]
2023-04-19 06:05:23 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:23 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:23 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-19 06:05:23 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:23 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):197 - sync summary: io.airbyte.config.StandardSyncOutput@66219265[standardSyncSummary=io.airbyte.config.StandardSyncSummary@5a7a8e01[status=failed,recordsSynced=0,bytesSynced=0,startTime=1681884321905,endTime=1681884323838,totalStats=io.airbyte.config.SyncStats@45cf210c[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=1681884323835,destinationWriteStartTime=1681884322111,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1681884323837,replicationStartTime=1681884321905,sourceReadEndTime=0,sourceReadStartTime=1681884322034,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@252be7ca[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@4ff3fbb0[stream=io.airbyte.protocol.models.AirbyteStream@41f76ec9[name=my_stream,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"url":{"description":"The URL for the API endpoint.","type":"string"},"token":{"description":"The API token for authentication.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@7d8cf0ba[failureOrigin=source,failureType=system_error,internalMessage='dict' object is not callable,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@7635d76[additionalProperties={attemptNumber=2, jobId=21, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
,retryable=<null>,timestamp=1681884323104,additionalProperties={}], io.airbyte.config.FailureReason@571d1851[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@2de6a55d[additionalProperties={attemptNumber=2, jobId=21, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1681884323282,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-19 06:05:23 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):202 - Sync summary length: 5352
2023-04-19 06:05:23 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-19 06:05:23 [32mINFO[m i.a.p.j.e.LoggingJobErrorReportingClient(reportJobFailureReason):26 - Report Job Error -> workspaceId: 8de5ffa5-23b6-4fa0-b972-ffe861132437, dockerImage: airbyte/source-customize-api:0.7.1, failureReason: io.airbyte.config.FailureReason@8002347[failureOrigin=source,failureType=system_error,internalMessage='dict' object is not callable,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@7fa31767[additionalProperties={attemptNumber=2, jobId=21, connector_command=read, from_trace_message=true}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
,retryable=<null>,timestamp=1681884323104,additionalProperties={}], metadata: {connector_repository=airbyte/source-customize-api, workspace_url=http://localhost:8000/workspaces/8de5ffa5-23b6-4fa0-b972-ffe861132437, failure_type=system_error, connector_command=read, connector_name=customize api 71, workspace_id=8de5ffa5-23b6-4fa0-b972-ffe861132437, airbyte_version=0.44.0, connection_url=http://localhost:8000/workspaces/8de5ffa5-23b6-4fa0-b972-ffe861132437/connections/6a98f420-d6f5-4c02-9086-65e0a5a7a49f, connector_definition_id=a7c495cb-ad44-43de-b60f-188cf269437f, failure_origin=source, connection_id=6a98f420-d6f5-4c02-9086-65e0a5a7a49f, connector_release_stage=custom, job_id=21, deployment_mode=OSS}
2023-04-19 06:05:24 [32mINFO[m i.a.c.f.EnvVariableFeatureFlags(autoDisablesFailingConnections):36 - Auto Disable Failing Connections: false
2023-04-19 06:05:08 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-19 06:05:08 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-19 06:05:09 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-19 06:05:09 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/0/logs.log
2023-04-19 06:05:09 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:09 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:09 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-19 06:05:09 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):93 - Setting up source...
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):97 - Setting up destination...
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-19 06:05:09 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):106 - Setting up replication worker...
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 21 attempt id: 0
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.my_stream=full_refresh - overwrite}
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-19 06:05:09 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-19 06:05:09 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-21-0-zvlky with resources io.airbyte.config.ResourceRequirements@34038137[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:09 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/0 --log-driver none --name destination-mysql-write-21-0-zvlky --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-19 06:05:09 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-19 06:05:09 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:09 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.7.1 exists...
2023-04-19 06:05:09 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.7.1 was found locally.
2023-04-19 06:05:09 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-21-0-hnynx with resources io.airbyte.config.ResourceRequirements@7dc2091c[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:09 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/0 --log-driver none --name source-customize-api-read-21-0-hnynx --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.7.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/source-customize-api:0.7.1 read --config source_config.json --catalog source_catalog.json
2023-04-19 06:05:09 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:09 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-19 06:05:09 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-19 06:05:10 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}"
2023-04-19 06:05:10 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-19 06:05:10 [44msource[0m > 'dict' object is not callable
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:10 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting..."
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed."
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=my_stream, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_dmr_my_stream, outputTableName=_airbyte_raw_my_stream, syncMode=overwrite}"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started."
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams"
2023-04-19 06:05:10 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:10 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream my_stream. schema: api, tmp table name: _airbyte_tmp_dmr_my_stream"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream my_stream. schema api, tmp table _airbyte_tmp_dmr_my_stream, final table _airbyte_raw_my_stream"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream my_stream. schema api, tmp table name: _airbyte_tmp_dmr_my_stream"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed."
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:11 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:11 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	... 4 more
2023-04-19 06:05:11 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1681884309230,
  "endTime" : 1681884311386,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1681884311386,
    "destinationWriteStartTime" : 1681884309466,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1681884311386,
    "replicationStartTime" : 1681884309230,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1681884309381,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-19 06:05:11 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "'dict' object is not callable",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 21,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 110, in read\n    stream_is_available, error = stream_instance.check_availability(logger, self)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 190, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 45, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 423, in read_records\n    yield from self._read_pages(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 439, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 456, in _fetch_next_page\n    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),\nTypeError: 'dict' object is not callable\n",
  "timestamp" : 1681884310609
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 0,
    "jobId" : 21,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1681884310739
} ]
2023-04-19 06:05:11 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:11 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):197 - sync summary: io.airbyte.config.StandardSyncOutput@4803dfa4[standardSyncSummary=io.airbyte.config.StandardSyncSummary@10523594[status=failed,recordsSynced=0,bytesSynced=0,startTime=1681884309230,endTime=1681884311386,totalStats=io.airbyte.config.SyncStats@29fcd8e8[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=1681884311386,destinationWriteStartTime=1681884309466,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1681884311386,replicationStartTime=1681884309230,sourceReadEndTime=0,sourceReadStartTime=1681884309381,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@3ba76429[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@6d0f6206[stream=io.airbyte.protocol.models.AirbyteStream@6c7004a6[name=my_stream,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"url":{"description":"The URL for the API endpoint.","type":"string"},"token":{"description":"The API token for authentication.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@2304ba58[failureOrigin=source,failureType=system_error,internalMessage='dict' object is not callable,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@2382043d[additionalProperties={attemptNumber=0, jobId=21, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
,retryable=<null>,timestamp=1681884310609,additionalProperties={}], io.airbyte.config.FailureReason@358b5d19[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@59b22a3a[additionalProperties={attemptNumber=0, jobId=21, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1681884310739,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-19 06:05:11 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):202 - Sync summary length: 5353
2023-04-19 06:05:11 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the most recent source actor catalog
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-19 06:05:11 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get state
2023-04-19 06:05:11 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to set attempt sync config
2023-04-19 06:05:11 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/1/logs.log
2023-04-19 06:05:11 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:11 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:11 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.7.1 exists...
2023-04-19 06:05:11 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.7.1 was found locally.
2023-04-19 06:05:11 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-check-21-1-qlmgp with resources io.airbyte.config.ResourceRequirements@33f9a520[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:11 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/1 --log-driver none --name source-customize-api-check-21-1-qlmgp --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.7.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/source-customize-api:0.7.1 check --config source_config.json
2023-04-19 06:05:11 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:12 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Attempting to connect to API at http://192.168.100.158:9098/category/build/0/unauthorized...
2023-04-19 06:05:12 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Response from http://192.168.100.158:9098/category/build/0/unauthorized: {'status': 0, 'message': None, 'data': [{'id': 1, 'name': 'Êï∞ÊçÆ‰ªìÂ∫ìÊ®°Âùó', 'description': 'Êï∞ÊçÆ‰ªìÂ∫ìÊ®°Âùó', 'parentId': None, 'idPath': None, 'params': None, 'systems': None, 'sort': 0, 'type': 0, 'status': 0, 'namespace': None, 'groupId': None, 'groupName': None, 'createTime': '2022-12-09T15:45:16', 'createBy': 'admin', 'updateTime': '2022-12-09T15:45:16', 'updateBy': 'admin', 'tagCount': 7, 'children': None, 'scopes': [{'id': 3, 'name': 'Êï∞ÊçÆÈõÜ', 'systemId': 1}]}], 'error': None}
2023-04-19 06:05:12 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection status: True
2023-04-19 06:05:12 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check connection success
2023-04-19 06:05:12 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check succeeded
2023-04-19 06:05:13 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@99e5e87[status=succeeded,message=<null>,additionalProperties={}]
2023-04-19 06:05:13 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:13 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/1/logs.log
2023-04-19 06:05:13 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:13 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:13 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-19 06:05:13 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-19 06:05:13 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-check-21-1-yxgzl with resources io.airbyte.config.ResourceRequirements@33f9a520[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:13 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/1 --log-driver none --name destination-mysql-check-21-1-yxgzl --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/destination-mysql:0.1.20 check --config source_config.json
2023-04-19 06:05:13 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Class path contains multiple SLF4J bindings.
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-19 06:05:13 [1;31mERROR[m i.a.c.i.LineGobbler(voidCall):149 - SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {check=null, config=source_config.json}"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: CHECK"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting..."
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed."
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(close):350 - HikariPool-1 - Shutdown initiated..."
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(close):352 - HikariPool-1 - Shutdown completed."
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:14 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:14 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:14 [32mINFO[m i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@508298f[status=succeeded,message=<null>,additionalProperties={}]
2023-04-19 06:05:14 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:14 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:14 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-04-19 06:05:14 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:15 [32mINFO[m i.a.c.t.s.DefaultTaskQueueMapper(getTaskQueue):31 - Called DefaultTaskQueueMapper getTaskQueue for geography auto
2023-04-19 06:05:15 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/21/1/logs.log
2023-04-19 06:05:15 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.0
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to save workflow id for cancellation
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source for heartbeat
2023-04-19 06:05:15 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the source definition
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):93 - Setting up source...
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):97 - Setting up destination...
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable METRIC_CLIENT: ''
2023-04-19 06:05:15 [33mWARN[m i.a.m.l.MetricClientFactory(initialize):60 - Metric client is already initialized to 
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.ReplicationWorkerFactory(create):106 - Setting up replication worker...
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):161 - start sync worker. job id: 21 attempt id: 1
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):163 - Committing states from replication activity
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):166 - Committing stats from replication activity
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- START REPLICATION -----
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(run):182 - configured sync modes: {null.my_stream=full_refresh - overwrite}
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:15 [32mINFO[m i.a.w.i.DefaultAirbyteDestination(start):92 - Running destination...
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/destination-mysql:0.1.20 exists...
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/destination-mysql:0.1.20 was found locally.
2023-04-19 06:05:15 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = destination-mysql-write-21-1-vayys with resources io.airbyte.config.ResourceRequirements@2d4e2d5d[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:15 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/1 --log-driver none --name destination-mysql-write-21-1-vayys --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/destination-mysql:0.1.20 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/destination-mysql:0.1.20 write --config destination_config.json --catalog destination_catalog.json
2023-04-19 06:05:15 [32mINFO[m i.a.w.i.VersionedAirbyteMessageBufferedWriterFactory(createWriter):41 - Writing messages to protocol version 0.2.0
2023-04-19 06:05:15 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-04-19 06:05:15 [32mINFO[m i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-customize-api:0.7.1 exists...
2023-04-19 06:05:15 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-customize-api:0.7.1 was found locally.
2023-04-19 06:05:15 [32mINFO[m i.a.w.p.DockerProcessFactory(create):133 - Creating docker container = source-customize-api-read-21-1-sevab with resources io.airbyte.config.ResourceRequirements@11aa8744[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-04-19 06:05:15 [32mINFO[m i.a.w.p.DockerProcessFactory(create):184 - Preparing command: docker run --rm --init -i -w /data/21/1 --log-driver none --name source-customize-api-read-21-1-sevab --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-customize-api:0.7.1 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e AIRBYTE_ROLE= -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=1 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.0 -e WORKER_JOB_ID=21 airbyte/source-customize-api:0.7.1 read --config source_config.json --catalog source_catalog.json
2023-04-19 06:05:15 [32mINFO[m i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromDstRunnable$4):310 - Destination output thread started.
2023-04-19 06:05:15 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):94 - Starting source heartbeat check. Will check every 1 minutes.
2023-04-19 06:05:15 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):376 - Replication thread started.
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: Class path contains multiple SLF4J bindings.
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: Found binding in [jar:file:/airbyte/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
2023-04-19 06:05:16 [43mdestination[0m > SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):136 - starting destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationCliParser(parseOptions):118 - integration args: {catalog=destination_catalog.json, write=null, config=destination_config.json}"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):123 - Running integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):124 - Command: WRITE"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):125 - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword order - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:16 [44msource[0m > Starting syncing SourceCustomizeAPI
2023-04-19 06:05:16 [44msource[0m > 'dict' object is not callable
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword airbyte_secret - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:16 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:16 \u001B[33mWARN\u001B[m c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword multiline - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword"
2023-04-19 06:05:17 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):438 - Source has no more messages, closing connection.
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.b.s.SshTunnel(getInstance):170 - Starting connection with method: NO_TUNNEL"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):80 - HikariPool-1 - Starting..."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m c.z.h.HikariDataSource(<init>):82 - HikariPool-1 - Start completed."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$toWriteConfig$0):98 - Write config: WriteConfig{streamName=my_stream, namespace=null, outputSchemaName=api, tmpTableName=_airbyte_tmp_ncj_my_stream, outputTableName=_airbyte_raw_my_stream, syncMode=overwrite}"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(startTracked):116 - class io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer started."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):123 - Preparing tmp tables in destination started for 1 streams"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):127 - Preparing tmp table in destination started for stream my_stream. schema: api, tmp table name: _airbyte_tmp_ncj_my_stream"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):133 - Preparing tables in destination completed."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):65 - Airbyte message consumer: succeeded."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.b.BufferedStreamConsumer(close):171 - executing on success close procedure."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.SqlOperations(onDestinationCloseOperations):138 - No onDestinationCloseOperations required for this destination."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):163 - Finalizing tables in destination started for 1 streams"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):168 - Finalizing stream my_stream. schema api, tmp table _airbyte_tmp_ncj_my_stream, final table _airbyte_raw_my_stream"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):181 - Executing finalization of tables."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):183 - Finalizing tables in destination completed."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):186 - Cleaning tmp tables in destination started for 1 streams"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):190 - Cleaning tmp table in destination started for stream my_stream. schema api, tmp table name: _airbyte_tmp_ncj_my_stream"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):195 - Cleaning tmp tables in destination completed."
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.b.IntegrationRunner(runInternal):171 - Completed integration: io.airbyte.integrations.base.ssh.SshWrappedDestination"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.i.VersionedAirbyteStreamFactory(toAirbyteMessage):360 - Deserialization failed: "2023-04-19 06:05:17 \u001B[32mINFO\u001B[m i.a.i.d.m.MySQLDestination(main):138 - completed destination: class io.airbyte.integrations.destination.mysql.MySQLDestination"
2023-04-19 06:05:17 [1;31mERROR[m i.a.w.g.DefaultReplicationWorker(replicate):278 - Sync worker failed.
io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
		at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.replicate(DefaultReplicationWorker.java:214) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:190) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:91) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
		at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$5(TemporalAttemptExecution.java:195) ~[io.airbyte-airbyte-workers-0.44.0.jar:?]
		at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440) ~[io.airbyte-airbyte-commons-worker-0.44.0.jar:?]
	... 4 more
2023-04-19 06:05:17 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "failed",
  "recordsSynced" : 0,
  "bytesSynced" : 0,
  "startTime" : 1681884315490,
  "endTime" : 1681884317759,
  "totalStats" : {
    "bytesCommitted" : 0,
    "bytesEmitted" : 0,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 0,
    "destinationWriteStartTime" : 1681884315676,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 0,
    "recordsCommitted" : 0,
    "replicationEndTime" : 1681884317758,
    "replicationStartTime" : 1681884315490,
    "sourceReadEndTime" : 0,
    "sourceReadStartTime" : 1681884315603,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ ]
}
2023-04-19 06:05:17 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ {
  "failureOrigin" : "source",
  "failureType" : "system_error",
  "internalMessage" : "'dict' object is not callable",
  "externalMessage" : "Something went wrong in the connector. See the logs for more details.",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 21,
    "from_trace_message" : true,
    "connector_command" : "read"
  },
  "stacktrace" : "Traceback (most recent call last):\n  File \"/airbyte/integration_code/main.py\", line 13, in <module>\n    launch(source, sys.argv[1:])\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 131, in launch\n    for message in source_entrypoint.run(parsed_args):\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py\", line 122, in run\n    for message in generator:\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py\", line 110, in read\n    stream_is_available, error = stream_instance.check_availability(logger, self)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py\", line 190, in check_availability\n    return self.availability_strategy.check_availability(self, logger, source)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py\", line 45, in check_availability\n    get_first_record_for_slice(stream, stream_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py\", line 38, in get_first_record_for_slice\n    return next(records_for_slice)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 423, in read_records\n    yield from self._read_pages(\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 439, in _read_pages\n    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)\n  File \"/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py\", line 456, in _fetch_next_page\n    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),\nTypeError: 'dict' object is not callable\n",
  "timestamp" : 1681884316823
}, {
  "failureOrigin" : "source",
  "internalMessage" : "Source didn't exit properly - check the logs!",
  "externalMessage" : "Something went wrong within the source connector",
  "metadata" : {
    "attemptNumber" : 1,
    "jobId" : 21,
    "connector_command" : "read"
  },
  "stacktrace" : "io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)\n\tat java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.\n\tat io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)\n\tat io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)\n\t... 4 more\n",
  "timestamp" : 1681884317166
} ]
2023-04-19 06:05:17 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-04-19 06:05:17 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:17 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - ----- END REPLICATION -----
2023-04-19 06:05:17 [32mINFO[m i.a.c.i.LineGobbler(voidCall):149 - 
2023-04-19 06:05:17 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):197 - sync summary: io.airbyte.config.StandardSyncOutput@14c9aaaf[standardSyncSummary=io.airbyte.config.StandardSyncSummary@7a4f2d6a[status=failed,recordsSynced=0,bytesSynced=0,startTime=1681884315490,endTime=1681884317759,totalStats=io.airbyte.config.SyncStats@f6a24dc[bytesCommitted=0,bytesEmitted=0,destinationStateMessagesEmitted=0,destinationWriteEndTime=0,destinationWriteStartTime=1681884315676,estimatedBytes=<null>,estimatedRecords=<null>,meanSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBeforeSourceStateMessageEmitted=0,maxSecondsBetweenStateMessageEmittedandCommitted=0,meanSecondsBetweenStateMessageEmittedandCommitted=0,recordsEmitted=0,recordsCommitted=0,replicationEndTime=1681884317758,replicationStartTime=1681884315490,sourceReadEndTime=0,sourceReadStartTime=1681884315603,sourceStateMessagesEmitted=0,additionalProperties={}],streamStats=[],additionalProperties={}],normalizationSummary=<null>,webhookOperationSummary=<null>,state=<null>,outputCatalog=io.airbyte.protocol.models.ConfiguredAirbyteCatalog@29ff2984[streams=[io.airbyte.protocol.models.ConfiguredAirbyteStream@703a62c6[stream=io.airbyte.protocol.models.AirbyteStream@739d35d6[name=my_stream,jsonSchema={"$schema":"http://json-schema.org/draft-07/schema","type":"object","required":["url"],"properties":{"url":{"description":"The URL for the API endpoint.","type":"string"},"token":{"description":"The API token for authentication.","type":"string"}}},supportedSyncModes=[full_refresh],sourceDefinedCursor=<null>,defaultCursorField=[],sourceDefinedPrimaryKey=[],namespace=<null>,additionalProperties={}],syncMode=full_refresh,cursorField=[],destinationSyncMode=overwrite,primaryKey=[],additionalProperties={}]],additionalProperties={}],failures=[io.airbyte.config.FailureReason@2d8fa3bd[failureOrigin=source,failureType=system_error,internalMessage='dict' object is not callable,externalMessage=Something went wrong in the connector. See the logs for more details.,metadata=io.airbyte.config.Metadata@7dec0c81[additionalProperties={attemptNumber=1, jobId=21, from_trace_message=true, connector_command=read}],stacktrace=Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 13, in <module>
    launch(source, sys.argv[1:])
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 131, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 122, in run
    for message in generator:
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 110, in read
    stream_is_available, error = stream_instance.check_availability(logger, self)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/core.py", line 190, in check_availability
    return self.availability_strategy.check_availability(self, logger, source)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/availability_strategy.py", line 45, in check_availability
    get_first_record_for_slice(stream, stream_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/utils/stream_helper.py", line 38, in get_first_record_for_slice
    return next(records_for_slice)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 423, in read_records
    yield from self._read_pages(
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 439, in _read_pages
    request, response = self._fetch_next_page(stream_slice, stream_state, next_page_token)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/streams/http/http.py", line 456, in _fetch_next_page
    params=self.request_params(stream_state=stream_state, stream_slice=stream_slice, next_page_token=next_page_token),
TypeError: 'dict' object is not callable
,retryable=<null>,timestamp=1681884316823,additionalProperties={}], io.airbyte.config.FailureReason@5e637da8[failureOrigin=source,failureType=<null>,internalMessage=Source didn't exit properly - check the logs!,externalMessage=Something went wrong within the source connector,metadata=io.airbyte.config.Metadata@444ad037[additionalProperties={attemptNumber=1, jobId=21, connector_command=read}],stacktrace=io.airbyte.workers.internal.exception.SourceException: Source didn't exit properly - check the logs!
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:442)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
	at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:150)
	at io.airbyte.workers.general.DefaultReplicationWorker.lambda$readFromSrcAndWriteToDstRunnable$8(DefaultReplicationWorker.java:440)
	... 4 more
,retryable=<null>,timestamp=1681884317166,additionalProperties={}]],commitStateAsap=true,additionalProperties={}]
2023-04-19 06:05:17 [32mINFO[m i.a.w.t.s.ReplicationActivityImpl(lambda$replicate$3):202 - Sync summary length: 5340
2023-04-19 06:05:17 [32mINFO[m i.a.c.t.TemporalUtils(withBackgroundHeartbeat):307 - Stopping temporal heartbeating...
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to get the most recent source actor catalog
2023-04-19 06:05:21 [32mINFO[m i.a.a.c.AirbyteApiClient(retryWithJitter):179 - Attempt 0 to Get a connection by connection Id